name: hello workflow
on:
  push:
jobs:
  hello:
    name: hello job
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello"

      - uses: actions/github-script@v6
        with:
          script: |
            console.log(JSON.stringify(context, undefined, 2))