on:
  workflow_run:
    workflows:
      - hello workflow
    types:
      - completed

jobs:
  get-context:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            console.log(JSON.stringify(context, undefined, 2))
            
      - run: echo ${{event.workflow_run.head_branch}}