on:
  workflow_run:
    workflows:
      - hello workflow
    types:
      - completed

jobs:
  get-context:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            import {context} from '@actions/github';
            console.log(context)
            console.log(context.eventName);