name: Test Workflow

on:
  workflow_dispatch:
  push:
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Hello World!"
        name: bash script
        shell: bash

      - uses: actions/setup-node@v3
        name: Set up Node environment
        with:
          node-version: '14'

  resuable:
    uses: steveo-grainger/test-reusable/.github/workflows/reusable-workflow.yml@main
    with:
      test-input: "overriding the input"

