on:
  workflow_dispatch:
  push:
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Hello World!"

  resuable:
    uses: steveo-grainger/test-reusable/.github/workflows/test-reusable.yml@main
    with:
      test-input: "overriding the input"
  