name: Test Workflow

on:
  workflow_dispatch:
  push:
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Hello World!"
      - uses: actions/setup-node@v3
        with:
          node-version: '14'

  resuable:
    uses: steveo-grainger/test-reusable/.github/workflows/test-reusable.yml@main
    with:
      test-input: "overriding the input"

