name: Test Workflow

on:
  workflow_dispatch:
    inputs:
      fail:
        type: choice
        default: 'ignore'
        description: "Which job should fail?"
        required: true
        options:
          - ignore
          - first
          - second
  push:
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Hello World!"
        name: bash script
        shell: bash

      - uses: actions/setup-node@v3
        name: Set up Node environment
        with:
          node-version: '14'

      - run: echo ${{ github.events.inputs.fail == 'first' }}
      - run:  echo ${{ github.events.inputs.fail }}

      - name: Fail the job
        if: ${{ github.events.inputs.fail == 'first' }}
        run: exit 1

  resuable:
    uses: steveo-grainger/test-reusable/.github/workflows/reusable-workflow.yml@main
    with:
      test-input: "overriding the input"
      fail: ${{ github.events.inputs.fail }}
